#!/bin/bash
# ==============================================================================
# MODULE 4 · SCRIPT 6 of 7 — COVERAGE GAPS AND LIMITATIONS
# ==============================================================================
# ONE NEW IDEA on top of Scripts 1-5: this module's portfolio artifact (per
# its README) requires "an explicit statement of the call set's limitations
# (coverage gaps, reference bias, filter thresholds used)". Every one of
# those three things was already COMPUTED by an earlier script — Script 2
# (mapping/coverage), Script 3 (filter thresholds), Script 4 (ploidy
# correction) — but nothing until now assembles them into the one place the
# portfolio artifact actually asks for. This script auto-fills the
# objective, machine-checkable part of "limitations" as its own first-class
# step, the same way Module 2's and Module 3's report scripts auto-fill
# their objective sections and leave only true judgment calls to the human
# (this module's Script 7 does that for the remaining interpretation).
#
# TEACHING NOTE — why this is a separate script from Script 7:
#   Everything this script writes is a fact about THIS run (a threshold
#   used, a percentage of the genome with zero coverage) — no biological
#   judgment is involved, so no script needs a human in the loop for it.
#   Script 7's report, by contrast, leaves an actual interpretation section
#   blank on purpose. Keeping the two separate mirrors Module 2's split
#   between what a script can state as fact and what only an analyst can
#   conclude from those facts.
#
# Input:  WORKDIR — expects mapping_bias_summary.tsv (Script 2) and the
#         variants/ directory (Scripts 3 and 4's outputs) to already exist.
# Output: LIMITATIONS.md in WORKDIR.
# ==============================================================================

set -o pipefail

WORKDIR="${1:-/scratch/$(whoami)/master_snp_pipeline}"
OUT="${WORKDIR}/LIMITATIONS.md"

echo "=================================================================="
echo " MODULE 4 / SCRIPT 6 — Assembling the objective limitations statement"
echo "=================================================================="
echo "Working directory: ${WORKDIR}"
echo ""

MAPPING_TSV="${WORKDIR}/mapping_bias_summary.tsv"
if [ ! -s "${MAPPING_TSV}" ]; then
    echo "[WARN] ${MAPPING_TSV} not found — run Script 2 first for coverage-gap data. Continuing with what is available."
fi

{
    echo "# Call set limitations"
    echo ""
    echo "Auto-generated by \`6_Coverage_Gaps_And_Limitations.sh\` — objective, computed"
    echo "facts only. See \`VARIANT_REPORT.md\` (Script 7) for the human-written"
    echo "interpretation this statement feeds into."
    echo ""
    echo "## Coverage gaps and reference/mapping bias (Script 2)"
    echo ""
    if [ -s "${MAPPING_TSV}" ]; then
        echo "| Sample | % mapped | % properly paired | Mean depth | % genome at 0x | Flag |"
        echo "|---|---|---|---|---|---|"
        tail -n +2 "${MAPPING_TSV}" | while IFS=$'\t' read -r sample pmap ppair depth zcov flag; do
            echo "| ${sample} | ${pmap}% | ${ppair}% | ${depth} | ${zcov}% | ${flag} |"
        done
    else
        echo "_Not available — Script 2 was not run._"
    fi
    echo ""

    echo "## Filter thresholds actually used"
    echo ""
    echo "- **Naive fixed filter (master_snp_pipeline.sh, Phase 3 Step F):** QUAL >= 20, DP >= 10, MQ >= 30, applied identically to every sample regardless of this cohort's own depth/quality distribution."
    echo "- **Data-driven filter (Script 3, \`*_filtered_v2.vcf\`):** per-sample thresholds set to max(naive value, this sample's own 10th-percentile QUAL/DP/MQ among its candidate calls), plus an explicit strand-bias exclusion (INFO/DP4-derived) the naive filter does not apply at all."
    echo "- Readers of any results below should confirm which of the two filtered VCF sets (\`_filtered.vcf\` vs \`_filtered_v2.vcf\`) they are actually looking at — they are not guaranteed to contain the same calls."
    echo ""

    echo "## Ploidy correction status (Script 4)"
    echo ""
    HAP_COUNT=$(ls "${WORKDIR}"/variants/*_raw_haploid.vcf 2>/dev/null | wc -l)
    if [ "${HAP_COUNT}" -gt 0 ]; then
        echo "Script 4 was run: \`--ploidy 1\` re-calling is available for ${HAP_COUNT} sample(s) as \`*_raw_haploid.vcf\`. Any results in this report that were NOT explicitly re-derived from those haploid-corrected files may still reflect calls made under \`bcftools call\`'s diploid default against this haploid bacterial reference — confirm before treating a heterozygous-genotype result as biological."
    else
        echo "**Script 4 was not run for this output set.** All variant calls referenced here were made under \`bcftools call\`'s default DIPLOID model against a HAPLOID bacterial reference (GCF_000006945.2, *Salmonella enterica* Typhimurium LT2). Any heterozygous genotype in this call set should be treated as an artifact of that mismatch, not as evidence of a real mixed/heterozygous state, until Script 4 has been run and its correction propagated forward."
    fi
    echo ""

    echo "## Reference and dataset provenance"
    echo ""
    echo "- Reference: GCF_000006945.2 (*Salmonella enterica* subsp. *enterica* serovar Typhimurium str. LT2, ASM694v2) — a single bacterial isolate's genome. Any structural variation between it and the isolates actually sequenced here (insertions, deletions, or genes absent from LT2) is invisible to a reference-based SNP caller by construction, not merely undetected."
    echo "- \`master_snp_pipeline.sh\`'s own built-in fallback sample list (used only when \`srr_list.txt\` is absent) is SRR11092056/SRR11092057 — verified via NCBI eutils to be SARS-CoV-2 metagenomic RNA-seq, not bacterial WGS, and incompatible with this reference. See this module's README for the verified worked-example accessions actually used."
} > "${OUT}"

echo "Wrote ${OUT}"
echo "=================================================================="
