#!/bin/bash
#SBATCH --partition=batch
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=8G
#SBATCH --time=03:00:00
###############################################################################
# 7_QC_Report_Generator.sh
# Module 1 (Raw Sequencing Reads & QC) — Script 7 of 7
# Run interactively on the LOGIN NODE after script 6 completes — this only
# reads existing output files and writes markdown; it does not need compute
# resources or a Slurm allocation.
#
# ONE NEW IDEA on top of script 6: everything this module produced (checksums,
# before/after QC, trimming rationale, pairing verdicts, a full command log)
# is scattered across separate files. This script assembles all of it into
# the SINGLE portfolio artifact the curriculum specifies for this module: "A
# concise QC report containing the data source, checksums, diagnostic
# figures, preprocessing rationale, command log, and acceptance criteria."
#
# USAGE:
#   ./7_QC_Report_Generator.sh
#   (run from /scratch/$(whoami)/module1_qc, after script 6 has completed)
###############################################################################

set -e
set -o pipefail

cd /scratch/$(whoami)/module1_qc 2>/dev/null || { echo "ERROR: module1_qc directory not found. Run scripts 1-6 first."; exit 1; }

SRR_LIST=("SRR40359383" "SRR40359384")
REPORT="QC_REPORT.md"
NOW="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

{
echo "# Raw Read QC Report — PRJNA1518998 (Mouse retina, Vanderbilt University Medical Center)"
echo ""
echo "Generated by 7_QC_Report_Generator.sh on ${NOW}"
echo ""
echo "## 1. Data source"
echo ""
echo "- **BioProject:** PRJNA1518998"
echo "- **GEO accession:** GSE345194"
echo "- **Organism:** Mus musculus"
echo "- **Study:** Effect of adipocyte depletion on the retina"
echo "- **Runs analyzed:** ${SRR_LIST[*]}"
echo ""
echo "## 2. Checksums (data integrity at retrieval)"
echo ""
echo '```'
for SRR in "${SRR_LIST[@]}"; do
    if [ -f "checksums/${SRR}_raw.md5" ]; then
        cat "checksums/${SRR}_raw.md5"
    else
        echo "${SRR}: NO CHECKSUM FILE FOUND — re-run script 1 or 6 for this sample."
    fi
done
echo '```'
echo ""
echo "## 3. Diagnostic QC — before and after trimming"
echo ""
echo "| Run | Raw FastQC | Trimmed FastQC | Combined MultiQC (raw) | Combined MultiQC (trimmed) |"
echo "|---|---|---|---|---|"
for SRR in "${SRR_LIST[@]}"; do
    RAW_OK="missing"; TRIM_OK="missing"
    [ -d "qc_before/${SRR}_1_fastqc" ] && RAW_OK="qc_before/${SRR}_{1,2}_fastqc/"
    [ -d "qc_after/${SRR}_1_clean_fastqc" ] && TRIM_OK="qc_after/${SRR}_{1,2}_clean_fastqc/"
    echo "| ${SRR} | ${RAW_OK} | ${TRIM_OK} | multiqc_raw_batch.html | multiqc_trimmed_batch.html |"
done
echo ""
echo "## 4. Preprocessing rationale"
echo ""
for SRR in "${SRR_LIST[@]}"; do
    echo "### ${SRR}"
    if [ -f "fastp_reports/${SRR}_THRESHOLD_RATIONALE.md" ]; then
        tail -n +3 "fastp_reports/${SRR}_THRESHOLD_RATIONALE.md"
    else
        echo "_No rationale file found for ${SRR} — this run may not have been trimmed yet._"
    fi
    echo ""
done
echo "## 5. Paired-end integrity verdicts"
echo ""
for SRR in "${SRR_LIST[@]}"; do
    echo "**${SRR}:**"
    echo '```'
    if [ -f "pairing_reports/${SRR}.txt" ]; then
        cat "pairing_reports/${SRR}.txt"
    else
        echo "No pairing report found — re-run script 5 or 6 for this sample."
    fi
    echo '```'
done
echo ""
echo "## 6. Command log"
echo ""
echo "Full per-sample stdout/stderr logs (fetch through trimmed FastQC) are preserved at:"
for SRR in "${SRR_LIST[@]}"; do
    echo "- \`logs/${SRR}_pipeline.log\`"
done
echo ""
echo "## 7. Acceptance criteria — is this sample ready to align?"
echo ""
echo "A run is READY TO ALIGN only if ALL of the following are true. Fill in PASS/FAIL for each run by hand after reviewing the sections above — this script reports what happened, it does not certify readiness for you."
echo ""
echo "| Criterion | ${SRR_LIST[0]} | ${SRR_LIST[1]} |"
echo "|---|---|---|"
echo "| Checksums recorded at retrieval | | |"
echo "| Raw FastQC reviewed (not just run) | | |"
echo "| Trimming decision backed by specific FastQC evidence (Section 4) | | |"
echo "| Post-trim FastQC re-checked, no new FAILs introduced | | |"
echo "| Paired-end integrity PASSED on both raw and trimmed reads | | |"
echo "| Read count after trimming still adequate for downstream analysis | | |"
echo ""
echo "## 8. Reflection questions (answer by hand)"
echo ""
echo "1. Did trimming change the interpretation of ANY FastQC module from FAIL/WARN to PASS? If not, was trimming still worth doing?"
echo "2. Is high duplication (if flagged) in these samples more likely a technical artifact or real biology, and what additional evidence would tell you which?"
echo "3. If a labmate handed you these two runs with no report at all, which single file above would you ask for first, and why?"
} > "${REPORT}"

echo "OK: wrote ${REPORT}"
echo "Open it, fill in Section 7's PASS/FAIL table and Section 8's answers by hand — those two sections are intentionally NOT auto-filled."


# ==============================================================================
# Nuances & Pitfalls
# ==============================================================================
# - Sections 1-6 are auto-filled from files this module's earlier scripts
#   already produced — that is exactly the point: the report should never
#   require you to re-remember facts that a script already recorded.
# - Sections 7-8 are deliberately left for a human to fill in by hand, the
#   same pattern used for the REPRODUCIBILITY_REFLECTION.md portfolio
#   artifact in Module 0's integrated capstone (script 10) — a checklist an
#   earlier script could tick off automatically is not a genuine reflection.
# - If you re-run script 6 with different fastp flags or a different sample
#   set, re-run THIS script afterward — QC_REPORT.md is a snapshot of
#   whatever is currently on disk, not a live-updating document.
# ==============================================================================
