#!/bin/bash
#SBATCH --job-name=qc04_fastp
#SBATCH --partition=batch
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=8G
#SBATCH --time=01:00:00

###############################################################################
# 4_Evidence_Based_Fastp_Trimming.sh
# Module 1 (Raw Sequencing Reads & QC) — Script 4 of 7
#
# ONE NEW IDEA on top of script 3: trimming should be a DECISION justified by
# evidence, not a default you always apply. This script reads the FastQC
# summary.txt verdicts produced in script 2/3 for one sample, decides which
# fastp flags are actually warranted, runs fastp with ONLY those flags, and
# writes a THRESHOLD_RATIONALE.md explaining the decision in plain language —
# the exact "preprocessing rationale" the curriculum's portfolio artifact
# requires. It then re-runs FastQC on the trimmed output so before/after can
# be compared directly.
###############################################################################

set -e
set -o pipefail

module load FastQC/0.11.9-Java-11
module load fastp/0.23.4-GCC-13.2.0

cd /scratch/$(whoami)/module1_qc
mkdir -p trimmed_reads fastp_reports qc_after

SRR="SRR40359383"
SUMMARY_1="qc_before/${SRR}_1_fastqc/summary.txt"
SUMMARY_2="qc_before/${SRR}_2_fastqc/summary.txt"

if [ ! -f "${SUMMARY_1}" ] || [ ! -f "${SUMMARY_2}" ]; then
    echo "ERROR: FastQC summaries for ${SRR} not found. Run script 2 (with --extract) first." >&2
    exit 1
fi

# ------------------------------------------------------------------------------
# THE CORE IDEA: read the evidence, THEN decide. This is the direct antidote
# to the curriculum's misconception "higher trimming stringency is not
# automatically better" — every flag added below is tied to a specific FAIL
# or WARN line, and flags are NOT added just because they exist.
# ------------------------------------------------------------------------------
FASTP_FLAGS=()
RATIONALE_LINES=()

if grep -qE "^(WARN|FAIL)\s+Adapter Content" "${SUMMARY_1}" "${SUMMARY_2}"; then
    FASTP_FLAGS+=("--detect_adapter_for_pe")
    RATIONALE_LINES+=("- Adapter trimming ENABLED: FastQC flagged Adapter Content as WARN/FAIL on at least one mate.")
else
    RATIONALE_LINES+=("- Adapter trimming SKIPPED: FastQC reported PASS on Adapter Content for both mates — no evidence of contamination to justify it.")
fi

if grep -qE "^(WARN|FAIL)\s+Per base sequence quality" "${SUMMARY_1}" "${SUMMARY_2}"; then
    FASTP_FLAGS+=("--cut_tail" "--cut_tail_mean_quality" "20")
    RATIONALE_LINES+=("- 3' quality trimming ENABLED (cut_tail, mean Q20 window): FastQC flagged per-base quality decay.")
else
    RATIONALE_LINES+=("- 3' quality trimming SKIPPED: per-base quality PASSED on both mates across their full length.")
fi

# A length floor is applied unconditionally — this is a SAFETY MINIMUM, not a
# quality-driven trim, so it is documented separately from the evidence-based
# flags above.
FASTP_FLAGS+=("--length_required" "36")
RATIONALE_LINES+=("- Minimum length floor of 36bp applied unconditionally: reads shorter than this are unusable for reliable alignment regardless of quality.")

echo "Chosen fastp flags: ${FASTP_FLAGS[*]}"

fastp -i "raw_reads/${SRR}_1.fastq" -I "raw_reads/${SRR}_2.fastq" \
      -o "trimmed_reads/${SRR}_1_clean.fastq" -O "trimmed_reads/${SRR}_2_clean.fastq" \
      "${FASTP_FLAGS[@]}" \
      --thread 4 \
      --json "fastp_reports/${SRR}_fastp.json" \
      --html "fastp_reports/${SRR}_fastp.html"

if [ ! -s "trimmed_reads/${SRR}_1_clean.fastq" ] || [ ! -s "trimmed_reads/${SRR}_2_clean.fastq" ]; then
    echo "ERROR: fastp did not produce two non-empty trimmed mate files. Stopping." >&2
    exit 1
fi

# ------------------------------------------------------------------------------
# Write the rationale document NOW, while the evidence and decision are both
# fresh — this is the file the module's portfolio-artifact report (script 7)
# will quote directly, so it must be written in plain language a reviewer who
# never saw this script can still follow.
# ------------------------------------------------------------------------------
{
    echo "# Trimming rationale for ${SRR}"
    echo ""
    echo "Generated by 4_Evidence_Based_Fastp_Trimming.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo ""
    echo "## FastQC evidence reviewed"
    printf '%s\n' "${RATIONALE_LINES[@]}"
    echo ""
    echo "## Command run"
    echo '```'
    echo "fastp -i raw_reads/${SRR}_1.fastq -I raw_reads/${SRR}_2.fastq -o trimmed_reads/${SRR}_1_clean.fastq -O trimmed_reads/${SRR}_2_clean.fastq ${FASTP_FLAGS[*]} --thread 4"
    echo '```'
} > "fastp_reports/${SRR}_THRESHOLD_RATIONALE.md"

echo "OK: rationale written to fastp_reports/${SRR}_THRESHOLD_RATIONALE.md"

# Re-run FastQC on the trimmed output so before/after can be compared directly.
fastqc "trimmed_reads/${SRR}_1_clean.fastq" "trimmed_reads/${SRR}_2_clean.fastq" -o qc_after -t 4 --extract

echo "Done: ${SRR} trimmed with evidence-based flags, re-QC'd into qc_after/."


# ==============================================================================
# Nuances & Pitfalls
# ==============================================================================
# - fastp applies its OWN internal default quality filters even with no flags
#   passed at all — "no flags" is not the same as "no filtering happened."
#   Always check the fastp JSON report's before/after read counts, not just
#   the flags you explicitly set.
# - This script's flag choices are intentionally conservative teaching
#   defaults (a single quality-trim mode, one length floor). A production
#   pipeline for a specific assay (e.g. small RNA, amplicon) would justify a
#   different, assay-specific set of flags — the POINT is the decision
#   process shown here, not that these exact flags are universally correct.
# - Re-running FastQC after trimming (qc_after/) is what makes "compare
#   before/after metrics" from the curriculum's workflow checkable, rather
#   than assumed. Script 6 automates this before/after comparison across all
#   samples; script 7 reports it in the portfolio artifact.
# ==============================================================================
